### ISSUE TITLE
wow, great integration! looking forward on it!

### ISSUE THREAD

**Issue by cofw2005** [alex-jung/ha-departures#14]
I am looking forward to this integration!
Have been using the Deutschbahn custom component, but it doesn't provided realtime delays for routes in Nürnberg. I just found this new integration, so excited and will try definitely.

**Comment by alex-jung** [comment]
> I am looking forward to this integration! Have been using the Deutschbahn custom component, but it doesn't provided realtime delays for routes in Nürnberg. I just found this new integration, so excited and will try definitely.

Thank you. Unfortunately EFA API used by integration doesn't provide real time information despite the explicit request :( I'm still looking for a solution for that - in case  I found something, it will be definitely part of integration in the future.
